"""Remove column_name from FMRI_History

Revision ID: a2ef831e12d8
Revises: fed61237516f
Create Date: 2025-03-11 23:27:00.273484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ef831e12d8'
down_revision: Union[str, None] = 'fed61237516f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fmri_history', 'scan_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fmri_history', sa.Column('scan_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
