"""Add scan_duration column to FMRI_History

Revision ID: d555b5f49d27
Revises: 49a3d0d24314
Create Date: 2025-03-11 23:23:44.390460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd555b5f49d27'
down_revision: Union[str, None] = '49a3d0d24314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fmri_history', sa.Column('scan_duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fmri_history', 'scan_duration')
    # ### end Alembic commands ###
